### ISSUE TITLE
Use dom-bind-notifier instead of puppet-dom-bind

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/Website#3]
The `dom-bind-notifier` https://github.com/Juicy/dom-bind-notifier should be used instead of hackish `puppet-dom-bind`.

**Comment by miyconst** [comment]
@tomalec I have refactored (https://github.com/Juicy/dom-bind-notifier/commit/8d2caf8a769eef2285e9b0fe324c8e5904f5ec04) the `notifyTemplate` method to simplify debugging, hope you don't mind.

**Comment by miyconst** [comment]
@tomalec I have pushed the necessary changes to test Website application with `dom-bind-notifier`.

You have to:

1. Run Website project.
2. Run Content project from the Website solution.
3. Go to http://localhost:8080/content/team/konstantin
4. Click the "Tomek Wytrębowicz" link, the `path` variable in the `notifyTemplate` will be `model.TemplateModel.Sections.1.Rows.1`, which is correct.
5. Click the "Marcin Warpechowski" link, the `path` variable in the `notifyTemplate` will be `model.TemplateModel.Sections.1.Rows.` which is wrong.

**Comment by warpech** [comment]
@tomalec assigining to you to fix the remaining problem. Thanks!

**Comment by warpech** [comment]
Already done
